"""Static characterization of the Type-K thermocouple conditioning circuit.

Every result is derived from the 8 measurement points documented in the
report (data/measurements.csv). Nothing is measured or simulated here.

Outputs (written to ../results/):
    characterization.md   - tables of fit parameters and residuals
    transfer_and_residuals.png

Run:
    pip install -r requirements.txt
    python characterize.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "measurements.csv"
OUT = ROOT / "results"

# Design values taken from the report (section 3).
R0_OHM = 1_000.0
R1_OHM = 175_000.0
DESIGN_SPAN_V = 2.5          # output at 350 degC (design target)
DESIGN_RANGE_C = 350.0
DESIGN_GAIN = R1_OHM / R0_OHM

# NIST ITS-90 Type K reference function, 0 degC to 1372 degC (emf in mV, t in degC).
# Source: NIST Monograph 175 / NIST ITS-90 Thermocouple Database.
_K_C = (
    -0.176004136860e-01, 0.389212049750e-01, 0.185587700320e-04,
    -0.994575928740e-07, 0.318409457190e-09, -0.560728448890e-12,
    0.560750590590e-15, -0.320207200030e-18, 0.971511471520e-22,
    -0.121047212750e-25,
)
_K_A = (0.118597600000e00, -0.118343200000e-03, 0.126968600000e03)


def type_k_emf_mv(t_c: float) -> float:
    """Type K thermoelectric voltage (mV) for a 0 degC reference junction."""
    poly = sum(c * t_c**i for i, c in enumerate(_K_C))
    a0, a1, a2 = _K_A
    return poly + a0 * math.exp(a1 * (t_c - a2) ** 2)


def load(path: Path) -> tuple[np.ndarray, np.ndarray]:
    rows = [r for r in path.read_text(encoding="utf-8").splitlines() if r and not r.startswith("#")]
    reader = csv.DictReader(rows)
    t, v = zip(*((float(r["temperature_C"]), float(r["vo_V"])) for r in reader))
    return np.array(t), np.array(v)


def linear_fit(x: np.ndarray, y: np.ndarray) -> dict:
    slope, offset = np.polyfit(x, y, 1)
    resid = y - (slope * x + offset)
    r2 = 1.0 - np.sum(resid**2) / np.sum((y - y.mean()) ** 2)
    return {"slope": slope, "offset": offset, "r2": r2, "resid": resid}


def analyse(t: np.ndarray, v: np.ndarray) -> dict:
    fit = linear_fit(t, v)

    # Expected circuit output if the only non-ideality were the Type K curve itself.
    v_k = DESIGN_GAIN * np.array([type_k_emf_mv(x) for x in t]) * 1e-3
    fit_k = linear_fit(t, v_k)
    corr = float(np.corrcoef(fit["resid"], fit_k["resid"])[0, 1])

    # Deviation from the design transfer line (0 V at 0 degC, 2.5 V at 350 degC).
    design_slope = DESIGN_SPAN_V / DESIGN_RANGE_C
    dev_design = v - design_slope * t

    # In-sample residuals after correction methods (same 8 points used to fit and evaluate).
    two_point_t = (v - v[0]) / (v[-1] - v[0]) * (t[-1] - t[0]) + t[0]
    lin_t = (v - fit["offset"]) / fit["slope"]
    emf = np.array([type_k_emf_mv(x) for x in t])
    k_gain, k_off = np.polyfit(emf, v, 1)          # v = k_gain * emf + k_off
    emf_est = (v - k_off) / k_gain
    grid = np.linspace(0, 400, 40001)
    grid_emf = np.array([type_k_emf_mv(x) for x in grid])
    table_t = np.interp(emf_est, grid_emf, grid)

    return {
        "fit": fit,
        "fit_k": fit_k,
        "resid_corr": corr,
        "design_slope": design_slope,
        "dev_design": dev_design,
        "k_gain": k_gain,
        "k_off": k_off,
        "err_two_point": two_point_t - t,
        "err_linear": lin_t - t,
        "err_table": table_t - t,
        "v_k": v_k,
    }


def write_markdown(t: np.ndarray, v: np.ndarray, a: dict, path: Path) -> None:
    f, fk = a["fit"], a["fit_k"]
    s_k = type_k_emf_mv(350) / 350 * 1e3
    lines = [
        "# Characterization results (generated by `analysis/characterize.py`)",
        "",
        "Derived from documented experimental measurements (8 points, single reading each).",
        "In-sample statistics only: the same points are used to fit and to evaluate.",
        "",
        "## Linear fit `Vo = S * T + Voff`",
        "",
        "| Parameter | Value |",
        "|---|---|",
        f"| Sensitivity S | {f['slope'] * 1e3:.4f} mV/degC |",
        f"| Offset Voff | {f['offset'] * 1e3:.1f} mV |",
        f"| R^2 | {f['r2']:.6f} |",
        f"| Max abs residual | {np.max(np.abs(f['resid'])) * 1e3:.2f} mV ({np.max(np.abs(f['resid'])) / f['slope']:.2f} degC equiv.) |",
        f"| RMS residual | {np.sqrt(np.mean(f['resid'] ** 2)) * 1e3:.2f} mV |",
        "",
        "## Comparison with design values",
        "",
        "| Quantity | Design / reference | Derived from data |",
        "|---|---|---|",
        f"| Transfer slope | {a['design_slope'] * 1e3:.4f} mV/degC (2.5 V / 350 degC) | {f['slope'] * 1e3:.4f} mV/degC |",
        f"| Expected slope from gain x Type K | {DESIGN_GAIN:.0f} x {s_k:.2f} uV/degC = {fk['slope'] * 1e3:.4f} mV/degC (linear fit of 175 x E_K) | {f['slope'] * 1e3:.4f} mV/degC ({(f['slope'] / fk['slope'] - 1) * 100:+.2f} %) |",
        f"| Output at 0 degC | 0 V | {v[0]:.3f} V |",
        f"| Output at 350 degC | 2.500 V | {v[-1]:.3f} V |",
        "",
        "## Per-point table",
        "",
        "| T (degC) | Vo meas. (V) | Fit resid. (mV) | Type K intrinsic resid. (mV) | Dev. from design line (mV) | Dev. (degC equiv.) |",
        "|---|---|---|---|---|---|",
    ]
    for i in range(len(t)):
        lines.append(
            f"| {t[i]:.0f} | {v[i]:.3f} | {f['resid'][i] * 1e3:+.2f} | {fk['resid'][i] * 1e3:+.2f} "
            f"| {a['dev_design'][i] * 1e3:+.1f} | {a['dev_design'][i] / a['design_slope']:+.1f} |"
        )
    lines += [
        "",
        f"Correlation between measured fit residuals and the intrinsic Type K residual pattern: r = {a['resid_corr']:.3f}.",
        "",
        "## Residual temperature error after correction (in-sample)",
        "",
        "| Correction method | Max abs error (degC) | RMS error (degC) |",
        "|---|---|---|",
    ]
    for name, key in (
        ("None (design transfer 2.5 V / 350 degC)", None),
        ("Two-point (0 and 350 degC endpoints)", "err_two_point"),
        ("Least-squares linear", "err_linear"),
        ("Gain/offset fit on emf + Type K inverse table", "err_table"),
    ):
        e = a["dev_design"] / a["design_slope"] if key is None else a[key]
        lines.append(f"| {name} | {np.max(np.abs(e)):.2f} | {np.sqrt(np.mean(e ** 2)):.2f} |")
    lines += [
        "",
        "These figures describe how well each correction model fits the documented points. They are",
        "not measurement accuracy: the reference temperature uncertainty, the voltmeter uncertainty and",
        "repeatability were not documented. Absolute measurement accuracy cannot be established from",
        "the available documentation.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def plot(t: np.ndarray, v: np.ndarray, a: dict, path: Path) -> None:
    surface, ink, ink2, grid = "#fcfcfb", "#0b0b0b", "#52514e", "#e4e3df"
    s1, s2 = "#2a78d6", "#eb6834"
    plt.rcParams.update({
        "font.size": 10, "axes.edgecolor": ink2, "axes.labelcolor": ink, "xtick.color": ink2,
        "ytick.color": ink2, "axes.spines.top": False, "axes.spines.right": False,
    })
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2), facecolor=surface)
    f = a["fit"]
    tt = np.linspace(0, 350, 2)

    ax1.set_facecolor(surface)
    ax1.plot(tt, a["design_slope"] * tt, "--", color=ink2, lw=1.2, label="Design target (2.5 V / 350 °C)")
    ax1.plot(tt, f["slope"] * tt + f["offset"], color=s1, lw=2, label="Least-squares fit")
    ax1.plot(t, v, "o", color=s1, ms=7, mec=surface, mew=2, label="Documented measurement")
    ax1.set(xlabel="Input temperature Tj (°C)", ylabel="Output Vo (V)", xlim=(-10, 360))
    ax1.set_title(
        f"Transfer function: S = {f['slope'] * 1e3:.3f} mV/°C, offset = {f['offset'] * 1e3:.0f} mV, "
        f"R² = {f['r2']:.5f}", fontsize=9.5, color=ink, loc="left",
    )
    ax1.grid(True, color=grid, lw=0.8)
    ax1.legend(frameon=False, fontsize=8.5, loc="upper left")

    ax2.set_facecolor(surface)
    ax2.axhline(0, color=ink2, lw=0.8)
    ax2.plot(t, a["fit_k"]["resid"] * 1e3, "-", color=s2, lw=2, marker="s", ms=6, mec=surface, mew=2,
             label="Expected from Type K curve (175 × E_K, NIST ITS-90)")
    ax2.plot(t, f["resid"] * 1e3, "-", color=s1, lw=2, marker="o", ms=7, mec=surface, mew=2,
             label="Measured (residual of linear fit)")
    ax2.set(xlabel="Input temperature Tj (°C)", ylabel="Residual from linear fit (mV)", xlim=(-10, 360))
    ax2.set_title(f"Nonlinearity residuals (r = {a['resid_corr']:.2f})", fontsize=9.5, color=ink, loc="left")
    ax2.margins(y=0.15)
    ax2.grid(True, color=grid, lw=0.8)
    ax2.legend(frameon=False, fontsize=8.5, loc="lower left")

    fig.text(0.01, 0.01, "Derived from the 8 documented measurement points (single reading each). "
             "Reference and voltmeter uncertainty not documented.", fontsize=8, color=ink2)
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(path, dpi=150, facecolor=surface)
    plt.close(fig)


def main() -> None:
    t, v = load(DATA)
    a = analyse(t, v)
    OUT.mkdir(exist_ok=True)
    write_markdown(t, v, a, OUT / "characterization.md")
    plot(t, v, a, OUT / "transfer_and_residuals.png")
    f = a["fit"]
    print(f"S = {f['slope'] * 1e3:.4f} mV/degC, Voff = {f['offset'] * 1e3:.1f} mV, R2 = {f['r2']:.6f}")
    print(f"Residual correlation with Type K intrinsic nonlinearity: r = {a['resid_corr']:.3f}")
    print(f"Wrote {OUT / 'characterization.md'} and {OUT / 'transfer_and_residuals.png'}")


if __name__ == "__main__":
    main()
