function Data_T = generate_example_data(n_hours, seed)
%GENERATE_EXAMPLE_DATA Synthetic hourly input data, for running the code only.
%
%   *** SYNTHETIC DATA. NOT THE ORIGINAL PROJECT DATA SET. ***
%   The original Data_T.mat used for the report is not in this repository.
%   Simulation results obtained with this data have no relation to the
%   figures published in the report and must not be presented as such.
%
%   Data_T = GENERATE_EXAMPLE_DATA(n_hours, seed) returns a struct with
%   column vectors G [W/m^2], wind [m/s], load [W], temp [degC] and
%   price [EUR/MWh], using simple deterministic shapes plus seeded noise.
%   Uses only base MATLAB/Octave functions (no toolboxes).

    if nargin < 1
        n_hours = 24 * 365;
    end
    if nargin < 2
        seed = 42;
    end
    rng(seed); % reproducible on a given MATLAB/Octave version

    h = (0:n_hours - 1)';
    hour_of_day = mod(h, 24);
    day = floor(h / 24);
    season = cos(2 * pi * (day - 172) / 365);          % +1 near day 172 (late June)

    % Irradiance: half-sine daylight window, seasonal amplitude, random cloudiness
    day_length = 12 + 3 * season;                      % [h]
    sunrise = 12 - day_length / 2;
    x = (hour_of_day - sunrise) ./ day_length;
    clear_sky = (700 + 250 * season) .* max(sin(pi * x), 0) .* (x >= 0 & x <= 1);
    cloud = 0.35 + 0.65 * rand(n_hours, 1);
    G = clear_sky .* cloud;

    % Wind: Weibull(k = 2, c = 6 m/s) via inverse CDF
    u = rand(n_hours, 1);
    wind = 6 * (-log(1 - u)).^(1 / 2);

    % Ambient temperature: seasonal + diurnal
    temp = 15 + 8 * season + 5 * sin(2 * pi * (hour_of_day - 9) / 24) + rand(n_hours, 1) - 0.5;

    % Load: ~5 kW mean with a daily profile
    load_W = 5000 * (1 + 0.3 * sin(2 * pi * (hour_of_day - 13) / 24)) .* (0.9 + 0.2 * rand(n_hours, 1));

    % Price: EUR/MWh with morning/evening peaks
    price = 80 + 30 * sin(2 * pi * (hour_of_day - 14) / 12) + 10 * rand(n_hours, 1);

    Data_T = struct('G', G, 'wind', wind, 'load', load_W, 'temp', temp, 'price', price);
    Data_T.description = 'SYNTHETIC example data generated by generate_example_data.m - not measured data';
end
